getport: fix missing stddef.h inclusion
getport.c uses offsetof() but does not include <stddef.h>. On glibc
this works because offsetof is pulled in transitively, but on musl it
is not available without the explicit include, causing:

  getport.c:459:41: error: implicit declaration of function 'offsetof'

Signed-off-by: Jaipaul Cheernam <jaipaul.cheernam@est.tech>
Signed-off-by: Steve Dickson <steved@redhat.com>