getport: Fix switch case on old compilers
Buildroot distro compiles with fairly old compilers, which defaults to
old C11 standard (some of still used compilers don't even have newer
standard than C11). Workaround code which requires C23 with using { }.

This fixes error:

    getport.c:460:3: error: a label can only be part of a statement and a declaration is not a statement
       size_t path_len = len - offsetof(struct sockaddr_un, sun_path);
       ^~~~~~

Fixes: 1a6dcd74 ("Removed warnings in nfs_sockaddr2universal()")
Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
Signed-off-by: Steve Dickson <steved@redhat.com>